---
- name: "[PROMETHEUS-APB][MAIN] MongoDB"
  debug:
    msg:
      - "Entering on Main:"
      - "  Mode: {{ mode }}"
      - "  State: {{ state | default('undefined') }}"
      - "  Plan: {{ _apb_plan_id }}"

- block:
  - name: "[PROMETHEUS APB][MAIN] Deploying Prometheus"
    include_tasks: prometheus.yml
    when: not PROMETHEUS_SECURED_DEPLOYMENT | bool

  - name: "[PROMETHEUS APB][MAIN] Deploying Prometheus-Oauth"
    include_tasks: prometheus-oauth.yml
    when: PROMETHEUS_SECURED_DEPLOYMENT | bool

  - name: "[PROMETHEUS APB][MAIN] Deploying Prometheus-AlertManager"
    include_tasks: prometheus-alertmanager.yml

  - name: "[PROMETHEUS APB][MAIN] Deploying Prometheus-Grafana"
    include_tasks: prometheus-grafana-oauth.yml
    when: DEPLOY_GRAFANA | bool
  when: mode == 'provision'

- block:
  - name: "[PROMETHEUS APB][MAIN] Deprovision Prometheus"
    include_tasks: deprovision.yml
  when: mode == 'deprovision'

- block:
  - name: "[PROMETHEUS APB][MAIN] Test Prometheus deployment"
    include_tasks: test.yml
  when: mode == 'test'

  # Recover Tests Results
- block:
  - name: "[PROMETHEUS APB][FINISH] Recover Tests Results"
    include_tasks: recover_tests.yml
  when: mode == 'finish_tests'

