---
- name: "[PROMETHEUS APB][TEST] Check the Prometheus server is accesible"
  uri:
    url: "https://{{ prometheus_route.route.spec.host }}"
    return_content: yes
    validate_certs: no
  register: webpage
  retries: 10
  delay: 20
  failed_when:
    - webpage.status == 403
    - '"Log in with OpenShift" not in webpage.content'
  until: '"Log in with OpenShift" in webpage.content'

  # - name: "[PROMETHEUS APB][TEST] Check the Graphana server is accesible"
  #   uri:
  #     url: "https://{{ grafana_route.route.spec.host }}"
  #     return_content: yes
  #     validate_certs: no
  #   register: webpage
  #   retries: 10
  #   delay: 20
  #   failed_when:
  #     - webpage.status == 403
  #     - '"Log in with OpenShift" not in webpage.content'
  #   until: '"Log in with OpenShift" in webpage.content'

