---
# - name: "[PROMETHEUS APB][MAIN] Entering Development mode" 
#   include_tasks: prometheus.yml
#   when: _apb_plan_id == "dev"
# 
# - name: "[PROMETHEUS APB][MAIN] Entering Production mode" 
#   include_tasks: prod.yml
#   when: _apb_plan_id == "prod"
- name: "[PROMETHEUS APB][MAIN] Deploying Prometheus"
  include_tasks: prometheus.yml

- name: "[PROMETHEUS APB][MAIN] Deploying Prometheus-AlertManager"
  include_tasks: prometheus-alertmanager.yml
