---
service_name: 'prometheus'
app_name: "{{ service_name }}-apb"
state: present

# Prometheus
prometheus_image: "registry.access.redhat.com/openshift3/prometheus"
prometheus_version: "latest"
prometheus_port: 9090
prometheus_configmap_name: "{{ service_name }}-configmap"
prometheus_configmap_rules_name: "{{ service_name }}-rules"
prometheus_configmap_volume_name: "{{ service_name }}-configmap-volume"
prometheus_data_volume_name: "{{ service_name }}-data"
prometheus_pvc_name: "{{ service_name }}-claim"
prometheus_secret_name: "prometheus"

# AlertManager
service_name_am: "{{ service_name }}-alertmanager"
prometheus_alertmanager_image: 'registry.access.redhat.com/openshift3/prometheus-alertmanager'
prometheus_alertmanager_version: 'latest'
prometheus_alertmanager_configmap_name: "{{ service_name_am }}-config-map"
prometheus_alertmanager_configmap_templates_name: "{{ service_name_am }}-templates-configmap"
prometheus_alertmanager_data_volume_name: "{{ service_name_am }}-data"
prometheus_alertmanager_port: 9093
prometheus_alertmanager_pvc_name: "{{ service_name_am }}-claim"

# AlertBuffer
prometheus_alertbuffer_image: 'registry.access.redhat.com/openshift3/prometheus-alert-buffer'
prometheus_alertbuffer_version: 'latest'

# Proxy
prometheus_proxy_name: "{{ lookup('env','PROM_OAUTH_PROXY_NAME') | default('oauth-proxy', true) }}"
prometheus_proxy_tag: "{{ lookup('env','PROM_OAUTH_PROXY_TAG') | default('v1.0.0', true) }}"
prometheus_proxy: "{{ registry }}/{{ prometheus_proxy_name }}:{{ prometheus_proxy_tag }}"
prometheus_proxy_port: 4180

# OAuth Proxy values
proxy_serviceaccount_name: "oauth-proxy"
proxy_image: "docker.io/openshift/oauth-proxy"
proxy_version: "v1.1.0"

