---
- name: "[PROMETHEUS APB][PROVISION] Provision application Prometheus APB"
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    state: 'present'
    mode: 'provision'
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: prometheus-apb
    playbook_debug: false
